//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubyLocke_Unit06_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Reserv_ID { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int NoOfDays { get; set; }
        public int NoOfPeople { get; set; }
        public string BedType { get; set; }
        public string SpecialRequests { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int GuestCustomerID { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
